### ISSUE TITLE
Could not resolve host: gitea-sqlite.lan                             

### ISSUE THREAD

**Issue by bao3** [hellvesper/iocage-plugin-paperless-ngx#1]
I tried to  install this plugin, but I Got the error :
```
fatal: unable to access 'http://gitea-sqlite.lan/vesper/iocage-plugin-paperless-ngx.git/': Could not resolve host: gitea-sqlite.lan   
Partial plugin destroyed                                             
```
the domain "gitea-sqlite.lan" is like an LAN domain , I don't know how to resolve

**Comment by hellvesper** [comment]
> I tried to install this plugin, but I Got the error :
> 
> ```
> fatal: unable to access 'http://gitea-sqlite.lan/vesper/iocage-plugin-paperless-ngx.git/': Could not resolve host: gitea-sqlite.lan   
> Partial plugin destroyed                                             
> ```
> 
> the domain "gitea-sqlite.lan" is like an LAN domain , I don't know how to resolve

should be fixed now

**Comment by bao3** [comment]
@hellvesper Thx, I could confirm that it is fixed. Thank you bro
